server {
    listen 10086;
    server_name _;

    location = / {
        proxy_pass http://v2ray-api:2016/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
    }

    location /ray {
        proxy_pass http://v2ray:10086;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_read_timeout 3600s;
    }

    location / {
        return 404;
    }
}
